/*
Copyright 2026 zhaizhicheng.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	flowv1alpha1 "github.com/workflow.sh/work-flow/pkg/apis/flow/v1alpha1"
	scheme "github.com/workflow.sh/work-flow/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// WorkTemplatesGetter has a method to return a WorkTemplateInterface.
// A group's client should implement this interface.
type WorkTemplatesGetter interface {
	WorkTemplates(namespace string) WorkTemplateInterface
}

// WorkTemplateInterface has methods to work with WorkTemplate resources.
type WorkTemplateInterface interface {
	Create(ctx context.Context, workTemplate *flowv1alpha1.WorkTemplate, opts v1.CreateOptions) (*flowv1alpha1.WorkTemplate, error)
	Update(ctx context.Context, workTemplate *flowv1alpha1.WorkTemplate, opts v1.UpdateOptions) (*flowv1alpha1.WorkTemplate, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, workTemplate *flowv1alpha1.WorkTemplate, opts v1.UpdateOptions) (*flowv1alpha1.WorkTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*flowv1alpha1.WorkTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*flowv1alpha1.WorkTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *flowv1alpha1.WorkTemplate, err error)
	WorkTemplateExpansion
}

// workTemplates implements WorkTemplateInterface
type workTemplates struct {
	*gentype.ClientWithList[*flowv1alpha1.WorkTemplate, *flowv1alpha1.WorkTemplateList]
}

// newWorkTemplates returns a WorkTemplates
func newWorkTemplates(c *FlowV1alpha1Client, namespace string) *workTemplates {
	return &workTemplates{
		gentype.NewClientWithList[*flowv1alpha1.WorkTemplate, *flowv1alpha1.WorkTemplateList](
			"worktemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *flowv1alpha1.WorkTemplate { return &flowv1alpha1.WorkTemplate{} },
			func() *flowv1alpha1.WorkTemplateList { return &flowv1alpha1.WorkTemplateList{} },
		),
	}
}
