/*
Copyright 2026 The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	flowv1alpha1 "github.com/workflow.sh/work-flow/pkg/apis/flow/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// WorkflowLister helps list Workflows.
// All objects returned here must be treated as read-only.
type WorkflowLister interface {
	// List lists all Workflows in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*flowv1alpha1.Workflow, err error)
	// Workflows returns an object that can list and get Workflows.
	Workflows(namespace string) WorkflowNamespaceLister
	WorkflowListerExpansion
}

// workflowLister implements the WorkflowLister interface.
type workflowLister struct {
	listers.ResourceIndexer[*flowv1alpha1.Workflow]
}

// NewWorkflowLister returns a new WorkflowLister.
func NewWorkflowLister(indexer cache.Indexer) WorkflowLister {
	return &workflowLister{listers.New[*flowv1alpha1.Workflow](indexer, flowv1alpha1.Resource("workflow"))}
}

// Workflows returns an object that can list and get Workflows.
func (s *workflowLister) Workflows(namespace string) WorkflowNamespaceLister {
	return workflowNamespaceLister{listers.NewNamespaced[*flowv1alpha1.Workflow](s.ResourceIndexer, namespace)}
}

// WorkflowNamespaceLister helps list and get Workflows.
// All objects returned here must be treated as read-only.
type WorkflowNamespaceLister interface {
	// List lists all Workflows in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*flowv1alpha1.Workflow, err error)
	// Get retrieves the Workflow from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*flowv1alpha1.Workflow, error)
	WorkflowNamespaceListerExpansion
}

// workflowNamespaceLister implements the WorkflowNamespaceLister
// interface.
type workflowNamespaceLister struct {
	listers.ResourceIndexer[*flowv1alpha1.Workflow]
}
