/*
Copyright 2026 zhaizhicheng.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	flowv1alpha1 "github.com/workflow.sh/work-flow/pkg/apis/flow/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// WorkTemplateLister helps list WorkTemplates.
// All objects returned here must be treated as read-only.
type WorkTemplateLister interface {
	// List lists all WorkTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*flowv1alpha1.WorkTemplate, err error)
	// WorkTemplates returns an object that can list and get WorkTemplates.
	WorkTemplates(namespace string) WorkTemplateNamespaceLister
	WorkTemplateListerExpansion
}

// workTemplateLister implements the WorkTemplateLister interface.
type workTemplateLister struct {
	listers.ResourceIndexer[*flowv1alpha1.WorkTemplate]
}

// NewWorkTemplateLister returns a new WorkTemplateLister.
func NewWorkTemplateLister(indexer cache.Indexer) WorkTemplateLister {
	return &workTemplateLister{listers.New[*flowv1alpha1.WorkTemplate](indexer, flowv1alpha1.Resource("worktemplate"))}
}

// WorkTemplates returns an object that can list and get WorkTemplates.
func (s *workTemplateLister) WorkTemplates(namespace string) WorkTemplateNamespaceLister {
	return workTemplateNamespaceLister{listers.NewNamespaced[*flowv1alpha1.WorkTemplate](s.ResourceIndexer, namespace)}
}

// WorkTemplateNamespaceLister helps list and get WorkTemplates.
// All objects returned here must be treated as read-only.
type WorkTemplateNamespaceLister interface {
	// List lists all WorkTemplates in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*flowv1alpha1.WorkTemplate, err error)
	// Get retrieves the WorkTemplate from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*flowv1alpha1.WorkTemplate, error)
	WorkTemplateNamespaceListerExpansion
}

// workTemplateNamespaceLister implements the WorkTemplateNamespaceLister
// interface.
type workTemplateNamespaceLister struct {
	listers.ResourceIndexer[*flowv1alpha1.WorkTemplate]
}
