/*
Copyright 2026 The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisflowv1alpha1 "github.com/workflow.sh/work-flow/pkg/apis/flow/v1alpha1"
	versioned "github.com/workflow.sh/work-flow/pkg/client/clientset/versioned"
	internalinterfaces "github.com/workflow.sh/work-flow/pkg/client/informers/externalversions/internalinterfaces"
	flowv1alpha1 "github.com/workflow.sh/work-flow/pkg/client/listers/flow/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// WorkTemplateInformer provides access to a shared informer and lister for
// WorkTemplates.
type WorkTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() flowv1alpha1.WorkTemplateLister
}

type workTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewWorkTemplateInformer constructs a new informer for WorkTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewWorkTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredWorkTemplateInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredWorkTemplateInformer constructs a new informer for WorkTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredWorkTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FlowV1alpha1().WorkTemplates(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FlowV1alpha1().WorkTemplates(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FlowV1alpha1().WorkTemplates(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FlowV1alpha1().WorkTemplates(namespace).Watch(ctx, options)
			},
		}, client),
		&apisflowv1alpha1.WorkTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *workTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredWorkTemplateInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *workTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisflowv1alpha1.WorkTemplate{}, f.defaultInformer)
}

func (f *workTemplateInformer) Lister() flowv1alpha1.WorkTemplateLister {
	return flowv1alpha1.NewWorkTemplateLister(f.Informer().GetIndexer())
}
