apiVersion: flow.workflow.sh/v1alpha1
kind: WorkTemplate
metadata:
  name: vcjob-template
  namespace: zzc-system
spec:
  gvr:
    group: batch.volcano.sh
    version: v1alpha1
    resource: jobs
  jobSpec:
    schedulerName: volcano
    minAvailable: 1
    tasks:
      - replicas: 1
        name: task-1
        template:
          spec:
            containers:
              - command:
                  - sleep
                  - "10"
                image: busybox
                name: task-1
            restartPolicy: OnFailure
---
apiVersion: flow.workflow.sh/v1alpha1
kind: WorkTemplate
metadata:
  name: pytorchjob-template
  namespace: zzc-system
spec:
  gvr:
    group: kubeflow.org
    version: v1
    resource: pytorchjobs
  jobSpec:
    pytorchReplicaSpecs:
      Master:
        replicas: 1
        restartPolicy: OnFailure
        template:
          spec:
            schedulerName: volcano
            containers:
              - name: pytorch
                image: busybox
                command: ["sleep", "10"]
            restartPolicy: OnFailure
      Worker:
        replicas: 1
        restartPolicy: OnFailure
        template:
          spec:
            schedulerName: volcano
            containers:
              - name: pytorch
                image: busybox
                command: ["sleep", "10"]
            restartPolicy: OnFailure
---
apiVersion: flow.workflow.sh/v1alpha1
kind: WorkTemplate
metadata:
  name: mpijob-template
  namespace: zzc-system
spec:
  gvr:
    group: kubeflow.org
    version: v1
    resource: mpijobs
  jobSpec:
    slotsPerWorker: 1
    cleanPodPolicy: None
    mpiReplicaSpecs:
      Launcher:
        replicas: 1
        template:
           spec:
             containers:
             - image: busybox
               name: mpi-launcher
               command: ["sleep", "10"]
      Worker:
        replicas: 1
        template:
          spec:
            containers:
            - image: busybox
              name: mpi-worker
              command: ["sleep", "10"]
---
apiVersion: flow.workflow.sh/v1alpha1
kind: WorkTemplate
metadata:
  name: paddlejob-template
  namespace: zzc-system
spec:
  gvr:
    group: kubeflow.org
    version: v1
    resource: paddlejobs
  jobSpec:
    cleanPodPolicy: Running
    paddleReplicaSpecs:
      Master:
        replicas: 1
        restartPolicy: OnFailure
        template:
          spec:
            containers:
              - name: paddle
                image: busybox
                command: ["sleep", "10"]
      Worker:
        replicas: 1
        restartPolicy: OnFailure
        template:
          spec:
            containers:
              - name: paddle
                image: busybox
                command: ["sleep", "10"]
---
apiVersion: flow.workflow.sh/v1alpha1
kind: WorkTemplate
metadata:
  name: deploy-template
  namespace: zzc-system
spec:
  gvr:
    group: apps
    version: v1
    resource: deployments
  jobSpec:
    replicas: 1
    selector:
      matchLabels:
        app: deploy-task
    template:
      metadata:
        labels:
          app: deploy-task
      spec:
        containers:
        - name: nginx
          image: busybox
          command: ["sleep", "10"]
