apiVersion: flow.workflow.sh/v1alpha1
kind: Workflow
metadata:
  name: sample-workflow
  namespace: zzc-system
spec:
  jobRetainPolicy: retain
  flows:
    - name: vcjob-template
    - name: pytorchjob-template
      dependsOn:
        targets:
          - vcjob-template
