apiVersion: flow.workflow.sh/v1alpha1
kind: Workflow
metadata:
  name: sample-workflow
  namespace: zzc-system
spec:
  jobRetainPolicy: delete
  flows:
    - name: pytorchjob-template
    - name: vcjob-template
      dependsOn:
        targets:
          - pytorchjob-template
    - name: paddlejob-template
      dependsOn:
        targets:
          - pytorchjob-template
    - name: mpijob-template
      dependsOn:
        targets:
          - vcjob-template
          - paddlejob-template
    - name: deploy-template
      dependsOn:
        targets:
          - mpijob-template
